### ISSUE TITLE
"Unexpected option '--use_tcp' found on command line." (Guppy 5.0.11)

### ISSUE THREAD

**Issue by hengjwj** [Psy-Fer/buttery-eel#26]
Hi James,

I followed the quickstart on the git page and installed buttery-eel 0.4.1 on my university's cluster but couldn't get it to run. Hope you can help. I used Guppy 5.0.11.

Here's how I ran it:

```shell
[s190075@hpc-g8003 HEK293T-WT-rep3]$ eel -g ~/bin/ont-guppy/bin/ --config /usr/local/ont-guppy-5.0.11/data/rna_r9.4.1_70bps_hac.cfg --device cuda:all -i ERR4706307_HEK293T-WT-rep3.blow5 -o HEK293T-WT-rep3.fastq

```

which returned:
```shell
Using port 5000
/home/s190075/bin/buttery-eel/venv3/bin/buttery-eel:15: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pk
g_resources.html
  from pkg_resources import load_entry_point

               ~  buttery-eel - SLOW5 Guppy/Dorado Basecalling  ~
                            version: 0.4.1
==========================================================================
  ARGS
==========================================================================
args:
 Namespace(barcode_kits=None, call_mods=False, config='/usr/local/ont-guppy-5.0.11/data/rna_r9.4.1_70bps_hac.cfg', detect_adapter=False, detect_mid_strand_ada
pter=False, detect_mid_strand_barcodes=False, do_read_splitting=False, enable_trim_barcodes=False, guppy_batchsize=4000, guppy_bin=PosixPath('/home/s190075/bi
n/ont-guppy/bin'), input='ERR4706307_HEK293T-WT-rep3.blow5', log='buttery_basecaller_logs', max_read_queue_size=20000, min_score_adapter=60.0, min_score_barco
de_front=60.0, min_score_barcode_mid=60.0, min_score_barcode_rear=60.0, min_score_read_splitting=50.0, moves_out=False, output='HEK293T-WT-rep3.fastq', procs=
4, profile=False, qscore=None, quiet=False, require_barcodes_both_ends=False, seq_sum=False, slow5_batchsize=4000, slow5_threads=4, trim_adapters=False)
['--device', 'cuda:all', '--port', '5000', '--use_tcp']


==========================================================================
  Starting Guppy/Dorado Basecalling Server
==========================================================================
Unexpected option '--use_tcp' found on command line.

Traceback (most recent call last):
  File "/home/s190075/bin/buttery-eel/venv3/bin/buttery-eel", line 33, in <module>
    sys.exit(load_entry_point('buttery-eel==0.4.1', 'console_scripts', 'buttery-eel')())
  File "/home/s190075/bin/buttery-eel/venv3/lib/python3.7/site-packages/buttery_eel-0.4.1-py3.7.egg/src/buttery_eel.py", line 855, in main
  File "/home/s190075/miniconda3/envs/sloweel/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/s190075/bin/buttery-eel/venv3/lib/python3.7/site-packages/buttery_eel-0.4.1-py3.7.egg/src/buttery_eel.py", line 97, in start_guppy_server_and_cl
ient
RuntimeError: Server couldn't be started

```

This is the cuda device I'm trying to use (if relevant):
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.106.00   Driver Version: 460.106.00   CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:B3:00.0 Off |                    0 |
| N/A   41C    P0    55W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

```

Looking forward to hearing from you!

**Comment by hasindu2008** [comment]
Hi

Latest Guppy 6.x server uses some ipc ports instead of tcp ports by default, which we found unreliable and thus pass this use_tcp flag inside butteryeel to force it to fall back to tcp ports. My guess is that in guppy 5, there isn't any ipc support and the default is tcp, causing this error.  @Psy-Fer will look into this soon.

Meanwhile, do you have a strict requirement to use guppy 5? Otherwise, if you use a newer  guppy like 6.5.7, this error will not happen. 

Nevertheless, we will fix this soon for older versions. 
@Psy-Fer we can look at the guppy change log and find from which version this flag is needed? Then pass it based on a version check?

**Comment by hengjwj** [comment]
Hi Hasindu, 

Thanks for the reply!

It would be preferable to use guppy 5 as I previously basecalled a sizeable number of runs using that version. Changing to guppy 6 now would mean having to re-run those again. 

I tried simply removing the --use_tcp flag too (really should have tried this earlier...) and it looks like it's running:

```shell
Using port 5000
/home/s190075/bin/buttery-eel/venv3/bin/buttery-eel:15: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point

               ~  buttery-eel - SLOW5 Guppy/Dorado Basecalling  ~
                            version: 0.4.1
==========================================================================
  ARGS
==========================================================================
args:
 Namespace(barcode_kits=None, call_mods=False, config='rna_r9.4.1_70bps_hac.cfg', detect_adapter=False, detect_mid_strand_adapter=False, detect_mid_strand_barcodes=False, do_read_splitting=False, enable_trim_barcodes=False, guppy_batchsize=4000, guppy_bin=PosixPath('/home/s190075/bin/ont-guppy/bin'), input='ERR4706307_HEK293T-WT-rep3.blow5', log='buttery_basecaller_logs', max_read_queue_size=20000, min_score_adapter=60.0, min_score_barcode_front=60.0, min_score_barcode_mid=60.0, min_score_barcode_rear=60.0, min_score_read_splitting=50.0, moves_out=False, output='HEK293T-WT-rep3.fastq', procs=4, profile=False, qscore=None, quiet=False, require_barcodes_both_ends=False, seq_sum=False, slow5_batchsize=4000, slow5_threads=4, trim_adapters=False)
['--device', 'cuda:all', '--port', '5000']


==========================================================================
  Starting Guppy/Dorado Basecalling Server
==========================================================================
Setting params...
Connecting...
[2023-11-01 14:18:33.731895] [0x00002b2b22bc8700] [info]    Connecting to server as ''
[2023-11-01 14:18:33.733678] [0x00002b2b22bc8700] [info]    Connected to server as ''. Connection id: 6018b617-5d27-46d2-870d-9ff6fa490f26
PyGuppyClient(address='localhost:5000', config='rna_r9.4.1_70bps_hac', alignment_index_file=None, bed_file=None, barcodes=None, status.connected, )
guppy/dorado started...
basecaller version: 5.0.11

==========================================================================
  Connecting to server
==========================================================================
Connection status:
status: status.connected
throttle: 0.01


==========================================================================
  Files
==========================================================================
Reading from: ERR4706307_HEK293T-WT-rep3.blow5
Output: HEK293T-WT-rep3.fastq
Writing to: HEK293T-WT-rep3.fastq

==========================================================================
  Basecalling
==========================================================================

[2023-11-01 14:18:34.496647] [0x00002b0d8d73f700] [info]    Connecting to server as ''
[2023-11-01 14:18:34.498859] [0x00002b0d8d73f700] [info]    Connected to server as ''. Connection id: 1774cfdb-c33a-4b94-a008-3cca5a02b5be
[2023-11-01 14:18:34.544511] [0x00002adae8322700] [info]    Connecting to server as ''
[2023-11-01 14:18:34.546891] [0x00002adae8322700] [info]    Connected to server as ''. Connection id: fecab174-a842-4db5-aa80-97faa8671170
[2023-11-01 14:18:34.550924] [0x00002b9fc32be700] [info]    Connecting to server as ''
[2023-11-01 14:18:34.552005] [0x00002b9fc32be700] [info]    Connected to server as ''. Connection id: 77dad755-9db3-44e9-8ab4-df1ae963b40d
[2023-11-01 14:18:34.560013] [0x00002b99ddbb9700] [info]    Connecting to server as ''
[2023-11-01 14:18:34.561137] [0x00002b99ddbb9700] [info]    Connected to server as ''. Connection id: fe221796-cc29-4542-9e29-9784eb8564e5
An exception occurred: TypeError - string indices must be integers
An exception occurred: TypeError - string indices must be integers
An exception occurred: TypeError - string indices must be integers
An exception occurred: TypeError - string indices must be integers
```

I'll update again if/when it finishes!

================================================================================

UPDATE:

I terminated the run as nothing new was being returned and the output fastq was still at 0KB after 40mins. Here's the log:

```shell
2023-11-01 14:18:29.809050 [guppy/message] ONT Guppy basecall server software version 5.0.11+2b6dbff, client-server API version 7.0.0
log path:            buttery_basecaller_logs
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:all
kernel path:         
runners per device:  4
2023-11-01 14:18:29.826183 [guppy/info] crashpad_handler not supported on this platform.
2023-11-01 14:18:29.826796 [guppy/info] Listening on port 5000.
2023-11-01 14:18:31.095969 [guppy/info] CUDA device 0 (compute 7.0) initialised, memory limit 34089730048B (33765982208B free)
2023-11-01 14:18:33.728106 [guppy/message] 
Config loaded:
config file:               /home/s190075/bin/ont-guppy/data/rna_r9.4.1_70bps_hac.cfg
model file:                /home/s190075/bin/ont-guppy/data/template_rna_r9.4.1_70bps_hac.jsn
model version id           2020-09-07_rna_r9.4.1_minion_256_8f8fc47b
adapter scaler model file: None
2023-11-01 14:18:33.729809 [guppy/message] Starting server on port: 5000
2023-11-01 14:18:33.733312 [guppy/info] client connection request. ["rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::"]
2023-11-01 14:18:33.733535 [guppy/info] New client connected Client 1 anonymous_client_1 id: 6018b617-5d27-46d2-870d-9ff6fa490f26 (connection string = 'rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::').
2023-11-01 14:18:34.497926 [guppy/info] client connection request. ["rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::"]
2023-11-01 14:18:34.498022 [guppy/info] New client connected Client 2 anonymous_client_2 id: 1774cfdb-c33a-4b94-a008-3cca5a02b5be (connection string = 'rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::').
2023-11-01 14:18:34.546708 [guppy/info] client connection request. ["rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::"]
2023-11-01 14:18:34.546783 [guppy/info] New client connected Client 3 anonymous_client_3 id: fecab174-a842-4db5-aa80-97faa8671170 (connection string = 'rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::').
2023-11-01 14:18:34.551883 [guppy/info] client connection request. ["rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::"]
2023-11-01 14:18:34.551930 [guppy/info] New client connected Client 4 anonymous_client_4 id: 77dad755-9db3-44e9-8ab4-df1ae963b40d (connection string = 'rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::').
2023-11-01 14:18:34.561001 [guppy/info] client connection request. ["rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::"]
2023-11-01 14:18:34.561048 [guppy/info] New client connected Client 5 anonymous_client_5 id: fe221796-cc29-4542-9e29-9784eb8564e5 (connection string = 'rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::').
2023-11-01 14:18:52.741900 [guppy/info] Client 2 anonymous_client_2 id: 1774cfdb-c33a-4b94-a008-3cca5a02b5be has disconnected.
2023-11-01 14:18:59.479029 [guppy/info] Client 3 anonymous_client_3 id: fecab174-a842-4db5-aa80-97faa8671170 has disconnected.
2023-11-01 14:19:05.695062 [guppy/info] Client 4 anonymous_client_4 id: 77dad755-9db3-44e9-8ab4-df1ae963b40d has disconnected.
2023-11-01 14:19:10.986255 [guppy/info] Client 5 anonymous_client_5 id: fe221796-cc29-4542-9e29-9784eb8564e5 has disconnected.

```

**Comment by hasindu2008** [comment]
@hengjwj sorry for the inconvenience.  We will investigate asap and let you know.

**Comment by Psy-Fer** [comment]
Hey, I just wanna quickly chime in.

I have found an issue.

The API on nanopore's side for this particular version only returns a single list, rather than a list of lists. As such, things did not go as planned in the basecall processing steps.

I am currently adding a case for this to be handled.

I'll let you know when it's done and tested.

Thanks again for all the info

James

**Comment by Psy-Fer** [comment]
Okay,

I have implemented a fix.

The gist of it is

if calls isn't a list, calls = [calls]

and then it plays nice. 
I fixed up some other things too where that old version doesn't provide some of the metadata, so I've hacked that in using other methods.

Could you try switching to the dev branch, and try that for your data?

It doesn't use TCP, so just do what you did above and it should all just work.

Let me know if you have any issues and I'll sort it out.

James

**Comment by hengjwj** [comment]
Hi James, 

Thanks for the fix. I switched to dev branch but unfortunately it doesn't seem to be working on my end. It returned the following:

```shell
[s190075@hpc-g8005 HEK293T-WT-rep3]$ eel -g ~/bin/ont-guppy/bin/ --config rna_r9.4.1_70bps_hac.cfg --device cuda:all -i ERR4706307_HEK293T-WT-rep3.blow5 -o HE
K293T-WT-rep3.fastq
Using port 5000
/home/s190075/bin/buttery-eel/venv3/bin/buttery-eel:15: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pk
g_resources.html
  from pkg_resources import load_entry_point

               ~  buttery-eel - SLOW5 Guppy/Dorado Basecalling  ~
                            version: 0.4.1
==========================================================================
  ARGS
==========================================================================
args:
 Namespace(barcode_kits=None, call_mods=False, config='rna_r9.4.1_70bps_hac.cfg', detect_adapter=False, detect_mid_strand_adapter=False, detect_mid_strand_bar
codes=False, do_read_splitting=False, enable_trim_barcodes=False, guppy_batchsize=4000, guppy_bin=PosixPath('/home/s190075/bin/ont-guppy/bin'), input='ERR4706
307_HEK293T-WT-rep3.blow5', log='buttery_basecaller_logs', max_read_queue_size=20000, min_score_adapter=60.0, min_score_barcode_front=60.0, min_score_barcode_
mid=60.0, min_score_barcode_rear=60.0, min_score_read_splitting=50.0, moves_out=False, output='HEK293T-WT-rep3.fastq', procs=4, profile=False, qscore=None, qu
iet=False, require_barcodes_both_ends=False, seq_sum=False, slow5_batchsize=4000, slow5_threads=4, trim_adapters=False)
['--device', 'cuda:all', '--port', '5000']


==========================================================================
  Starting Guppy/Dorado Basecalling Server
==========================================================================
Setting params...
Connecting...
[2023-11-03 15:51:55.273517] [0x00002ae3ffeae700] [info]    Connecting to server as ''
[2023-11-03 15:51:55.276017] [0x00002ae3ffeae700] [info]    Connected to server as ''. Connection id: fecd05b4-0354-4ec5-9576-ef84f6508bda
PyGuppyClient(address='localhost:5000', config='rna_r9.4.1_70bps_hac', alignment_index_file=None, bed_file=None, barcodes=None, status.connected, )
guppy/dorado started...
basecaller version: 5.0.11

==========================================================================
  Connecting to server
==========================================================================
```

Here are the contents of the logfile generated:

```shell
2023-11-03 15:51:53.168880 [guppy/message] ONT Guppy basecall server software version 5.0.11+2b6dbff, client-server API version 7.0.0
log path:            buttery_basecaller_logs
chunk size:          2000
chunks per runner:   512
max queued reads:    2000
num basecallers:     4
num socket threads:  2
max returned events: 50000
gpu device:          cuda:all
kernel path:         
runners per device:  4
2023-11-03 15:51:53.170909 [guppy/info] crashpad_handler not supported on this platform.
2023-11-03 15:51:53.171400 [guppy/info] Listening on port 5000.
2023-11-03 15:51:54.289131 [guppy/info] CUDA device 0 (compute 7.0) initialised, memory limit 34089730048B (33765982208B free)
2023-11-03 15:51:55.269035 [guppy/message] 
Config loaded:
config file:               /home/s190075/bin/ont-guppy/data/rna_r9.4.1_70bps_hac.cfg
model file:                /home/s190075/bin/ont-guppy/data/template_rna_r9.4.1_70bps_hac.jsn
model version id           2020-09-07_rna_r9.4.1_minion_256_8f8fc47b
adapter scaler model file: None
2023-11-03 15:51:55.271226 [guppy/message] Starting server on port: 5000
2023-11-03 15:51:55.275723 [guppy/info] client connection request. ["rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::"]
2023-11-03 15:51:55.275825 [guppy/info] New client connected Client 1 anonymous_client_1 id: fecd05b4-0354-4ec5-9576-ef84f6508bda (connection string = 'rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::').
2023-11-03 15:51:55.674364 [guppy/info] client connection request. ["rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::"]
2023-11-03 15:51:55.674446 [guppy/info] New client connected Client 2 anonymous_client_2 id: e1c5398e-ccb8-43db-94c2-33da95cee380 (connection string = 'rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::').
2023-11-03 15:51:55.715287 [guppy/info] client connection request. ["rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::"]
2023-11-03 15:51:55.715359 [guppy/info] New client connected Client 3 anonymous_client_3 id: a1b9d6e2-bf17-4d7f-abb8-a4912841a1d8 (connection string = 'rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::').
2023-11-03 15:51:55.729549 [guppy/info] client connection request. ["rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::"]
2023-11-03 15:51:55.729625 [guppy/info] New client connected Client 4 anonymous_client_4 id: 6480a2d9-468b-40bf-9993-20e2b7116488 (connection string = 'rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::').
2023-11-03 15:51:55.733968 [guppy/info] client connection request. ["rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::"]
2023-11-03 15:51:55.734022 [guppy/info] New client connected Client 5 anonymous_client_5 id: 54a84aaa-f7f2-4272-a57d-eb5a2775a2ad (connection string = 'rna_r9.4.1_70bps_hac:>timeout_interval=15000>client_name=>alignment_type=auto:::').
2023-11-03 15:52:05.763532 [guppy/info] Client 2 anonymous_client_2 id: e1c5398e-ccb8-43db-94c2-33da95cee380 has disconnected.
2023-11-03 15:52:13.316253 [guppy/info] Client 3 anonymous_client_3 id: a1b9d6e2-bf17-4d7f-abb8-a4912841a1d8 has disconnected.
2023-11-03 15:52:19.237017 [guppy/info] Client 4 anonymous_client_4 id: 6480a2d9-468b-40bf-9993-20e2b7116488 has disconnected.
2023-11-03 15:52:25.542287 [guppy/info] Client 5 anonymous_client_5 id: 54a84aaa-f7f2-4272-a57d-eb5a2775a2ad has disconnected.
2023-11-03 15:54:52.308926 [guppy/info] Client 1 anonymous_client_1 id: fecd05b4-0354-4ec5-9576-ef84f6508bda has disconnected.

```

Dummy question - after switching to dev branch, do I need to re-run this line from the quickstart?
>python setup.py install

**Comment by Psy-Fer** [comment]
Hey,

okay so when you switch branches. Then do a 

```
git pull
```

then check the requirements.txt file has the right version, so change it to 5.0.11 if you need to

Then source your env and re-install

```
source ./venv3/bin/activate
pip install .
deactivate
```

then run your eel script again

Let me know how that goes

James

**Comment by hengjwj** [comment]
Hi James, 

Thanks for the guide! Eventually got it to run. I had to rebuild my venv using python 3.8 (used 3.8.16).

It's currently ongoing but looks promising:

```shell
[s190075@hpc-g8003 HEK293T-WT-rep3]$ eel -g ~/bin/ont-guppy/bin/ --config rna_r9.4.1_70bps_hac.cfg --device cuda:all -i ERR4706307_HEK293T-WT-rep3.blow
5 -o HEK293T-WT-rep3.fastq
Using port 5000

               ~  buttery-eel - SLOW5 Guppy/Dorado Basecalling  ~
                            version: 0.4.1
==========================================================================
  ARGS
==========================================================================
args:
 Namespace(barcode_kits=None, call_mods=False, config='rna_r9.4.1_70bps_hac.cfg', detect_adapter=False, detect_mid_strand_adapter=False, detect_mid_strand_bar
codes=False, do_read_splitting=False, enable_trim_barcodes=False, guppy_batchsize=4000, guppy_bin=PosixPath('/home/s190075/bin/ont-guppy/bin'), input='ERR4706
307_HEK293T-WT-rep3.blow5', log='buttery_basecaller_logs', max_read_queue_size=20000, min_score_adapter=60.0, min_score_barcode_front=60.0, min_score_barcode_
mid=60.0, min_score_barcode_rear=60.0, min_score_read_splitting=50.0, moves_out=False, output='HEK293T-WT-rep3.fastq', procs=4, profile=False, qscore=None, qu
iet=False, require_barcodes_both_ends=False, seq_sum=False, slow5_batchsize=4000, slow5_threads=4, trim_adapters=False)
['--device', 'cuda:all', '--port', '5000']


==========================================================================
  Starting Guppy/Dorado Basecalling Server
==========================================================================
Setting params...
Connecting...
[2023-11-03 16:31:03.786349] [0x00002af3ed964700] [info]    Connecting to server as ''
[2023-11-03 16:31:03.789097] [0x00002af3ed964700] [info]    Connected to server as ''. Connection id: 980116f7-8011-49a5-a7b2-464d1f546053
PyGuppyClient(address='localhost:5000', config='rna_r9.4.1_70bps_hac', alignment_index_file=None, bed_file=None, barcodes=None, status.connected, )
guppy/dorado started...
basecaller version: 5.0.11

==========================================================================
  Connecting to server
==========================================================================
Connection status:
status: status.connected
throttle: 0.01


==========================================================================
  Files
==========================================================================
Reading from: ERR4706307_HEK293T-WT-rep3.blow5
Output: HEK293T-WT-rep3.fastq
Writing to: HEK293T-WT-rep3.fastq

==========================================================================
  Basecalling
==========================================================================

[2023-11-03 16:31:04.468317] [0x00002b87504dc700] [info]    Connecting to server as ''
[2023-11-03 16:31:04.468563] [0x00002b99bd750700] [info]    Connecting to server as ''
[2023-11-03 16:31:04.469880] [0x00002b99bd750700] [info]    Connected to server as ''. Connection id: 34e4866c-656c-44ce-a79d-946d95f9ba90
[2023-11-03 16:31:04.470613] [0x00002b87504dc700] [info]    Connected to server as ''. Connection id: c77feb23-2cb3-42cf-9604-0f075c4f0579
[2023-11-03 16:31:04.478677] [0x00002abe290a2700] [info]    Connecting to server as ''
[2023-11-03 16:31:04.479749] [0x00002abe290a2700] [info]    Connected to server as ''. Connection id: 4d23ed7b-8a92-4b2e-b419-fa78b537294e
[2023-11-03 16:31:04.479762] [0x00002abbfeb19700] [info]    Connecting to server as ''
[2023-11-03 16:31:04.480812] [0x00002abbfeb19700] [info]    Connected to server as ''. Connection id: f440d6ca-45bd-4a28-b28e-54ed9d0a58cc
processed reads: 50
processed reads: 100
processed reads: 150
processed reads: 200
processed reads: 250
processed reads: 300
processed reads: 350
processed reads: 400
processed reads: 450
processed reads: 500
processed reads: 1000
processed reads: 1500

```

**Comment by Psy-Fer** [comment]
Huzzah!

Yea nice work.

That's working.

James

**Comment by hengjwj** [comment]
Thanks for the help guys!

**Comment by Psy-Fer** [comment]
Thanks for the name change, that's very helpful.

Thanks for the detailed feedback, it helped me track down the issues and fix them.

**Comment by hasindu2008** [comment]
Fantastic :D
