### ISSUE TITLE
Error with exit code

### ISSUE THREAD

**Issue by hasindu2008** [Psy-Fer/buttery-eel#50]
Not sure if this is something fixed in a newer version as I am still using an old version. The issue is around returning the correct exit status.

```
==========================================================================
  Basecalling
==========================================================================

[guppy/error] basecall_core::CUDACaller::thread_main: Exception in CUDACaller worker thread: Could not allocate CUDA shared buffer for runner, size 5203847936
terminate called after throwing an instance of 'std::runtime_error'
  what():  Could not allocate CUDA shared buffer for runner, size 5203847936
[guppy/error] basecall_service::BasecallClient::worker_loop: Connection error. [timed_out] Timeout waiting for reply to request: LOAD_CONFIG
Process basecall_worker_3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/data/install/buttery-eel-0.4.1+guppy6.5.7/venv3/lib/python3.8/site-packages/src/buttery_eel.py", line 495, in submit_read
    result = client.pass_read(
  File "/data/install/buttery-eel-0.4.1+guppy6.5.7/venv3/lib/python3.8/site-packages/pyguppy_client_lib/pyclient.py", line 245, in pass_read
    raise ConnectionError(
ConnectionError: Not connected to server. status code: <status.loading_config: 2>. PyGuppyClient(address='localhost:5000', config='dna_r9.4.1_450bps_sup', align_ref=None, bed_file=None, barcodes=None, status.loading_config, )
[guppy/error] basecall_service::BasecallClient::worker_loop: Connection error. [timed_out] Timeout waiting for reply to request: LOAD_CONFIG


Basecalling complete!
```

The program exists with 0 status and thus in a script the error check does not get triggered. Also that Basecalling complete should perhaps print basecalling failed :( ?

**Comment by hasindu2008** [comment]
```
 /install/buttery-eel-0.5.0+dorado7.4.12/scripts/eel  --config dna_r9.4.1_450bps_hac.cfg --device auto -i f.blow5 -o reads.fastq && echo a
 ```

**Comment by Psy-Fer** [comment]
part of #66

**Comment by Psy-Fer** [comment]
fixed in https://github.com/Psy-Fer/buttery-eel/releases/tag/v0.7.0
